### ISSUE TITLE
Scrolling on the map does not zoom in/out

### ISSUE THREAD

**Issue by rogerpueyo** [agustim/fiberfy-server#12]
The common behaviour in these sort of maps is that scrolling up/down zooms the map in/out.

**Comment by agustim** [comment]
Revisar : https://github.com/agustim/fiberfy-server/blob/master/client/bpm.js#L129

Aquí hi ha un cas semblant http://gis.stackexchange.com/questions/111887/leaflet-mouse-wheel-zoom-only-after-click-on-map#111888

**Comment by agustim** [comment]
Migat a https://github.com/guifi/fiberfy-server/issues/11
